class Constants {
  static const List<String> pakistanCities = [
    "Abbottabad",
    "Ahmadpur East",
    "Ali Pur",
    "Arifwala",
    "Attock",
    "Bahawalnagar",
    "Bahawalpur",
    "Bannu",
    "Barkhan",
    "Batkhela",
    "Bhalwal",
    "Bhakkar",
    "Burewala",
    "Chakwal",
    "Charsadda",
    "Chiniot",
    "Chishtian",
    "Chitral",
    "Dadu",
    "Daska",
    "Dera Ghazi Khan",
    "Dera Ismail Khan",
    "Faisalabad",
    "Ghotki",
    "Gujranwala",
    "Gujrat",
    "Gwadar",
    "Hafizabad",
    "Hangu",
    "Haripur",
    "Hyderabad",
    "Islamabad",
    "Jacobabad",
    "Jafarabad",
    "Jalalpur Jattan",
    "Jaranwala",
    "Jatoi",
    "Jhang",
    "Jhelum",
    "Kamalia",
    "Kamoke",
    "Karachi",
    "Kasur",
    "Kharian",
    "Khairpur",
    "Khushab",
    "Kohat",
    "Kot Addu",
    "Kotli",
    "Lahore",
    "Larkana",
    "Layyah",
    "Lodhran",
    "Loralai",
    "Mandi Bahauddin",
    "Mansehra",
    "Mardan",
    "Mian Channu",
    "Mianwali",
    "Mirpur",
    "Mirpur Khas",
    "Multan",
    "Muzaffargarh",
    "Muzaffarabad",
    "Nawabshah",
    "Nowshera",
    "Okara",
    "Pakpattan",
    "Peshawar",
    "Quetta",
    "Rahim Yar Khan",
    "Rawalpindi",
    "Sadiqabad",
    "Sahiwal",
    "Sanghar",
    "Sargodha",
    "Sheikhupura",
    "Shikarpur",
    "Sialkot",
    "Sibi",
    "Skardu",
    "Sukkur",
    "Swabi",
    "Swat",
    "Tando Adam",
    "Tando Allahyar",
    "Tando Muhammad Khan",
    "Turbat",
    "Vehari",
    "Wah Cantt",
    "Zhob",
    "Ziarat",
  ];

  static const List<String> carModels = [
    "Toyota Corolla",
    "Honda Civic",
    "Suzuki Cultus",
    "Toyota Camry",
    "Honda City",
    "Suzuki Swift",
    "Toyota Prius",
    "Kia Sportage",
    "Hyundai Elantra",
    "Other",
  ];
}
